### ISSUE TITLE
Contribute stack collapser back to Flamegraph repository

### ISSUE THREAD

**Issue by ravn** [billybong/JavaFlames#1]
I've had a look at this repository and found it very useful, but decided I wanted the SVG instead of the HTML rendering and found that it was rather easy to adapt your code to create a Java stackcollapser from which `./flamegraph.pl` in https://github.com/brendangregg/FlameGraph could be fed directly.

Would you be ok with me extracting this functionality and contributing it back to the FlameGraph repository?  I think a single file Java program as you did it, fits the mindset rather well.

**Comment by billybong** [comment]
Sorry for late reply, but absolutely - feel free!
